import { v4 as uuidv4 } from 'uuid';
import { CoursesSeed } from './courses.seed';

// Mock data for modules
export const ModulesSeed = [
  // Modules for "JavaScript Essentials"
  {
    id: uuidv4(),
    title: 'Introduction to JavaScript',
    courseId: CoursesSeed[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'JavaScript Basics',
    courseId: CoursesSeed[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Modules for "Advanced JavaScript Techniques"
  {
    id: uuidv4(),
    title: 'Asynchronous JavaScript',
    courseId: CoursesSeed[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'JavaScript Design Patterns',
    courseId: CoursesSeed[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Modules for "Full-Stack Web Development"
  {
    id: uuidv4(),
    title: 'Front-End Development',
    courseId: CoursesSeed[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Back-End Development',
    courseId: CoursesSeed[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Modules for "Node.js and Express.js"
  {
    id: uuidv4(),
    title: 'Introduction to Node.js',
    courseId: CoursesSeed[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Building REST APIs with Express.js',
    courseId: CoursesSeed[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Modules for "React for Beginners"
  {
    id: uuidv4(),
    title: 'Getting Started with React',
    courseId: CoursesSeed[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'React Components and State',
    courseId: CoursesSeed[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: uuidv4(),
    title: 'Python Basics',
    courseId: CoursesSeed[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Python Data Structures',
    courseId: CoursesSeed[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Python File Input/Output',
    courseId: CoursesSeed[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C++ Basics',
    courseId: CoursesSeed[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C++ Data Types and Variables',
    courseId: CoursesSeed[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C++ Control Structures',
    courseId: CoursesSeed[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C++ Functions',
    courseId: CoursesSeed[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C++ Arrays and Pointers',
    courseId: CoursesSeed[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'NestJS Core Concepts',
    courseId: CoursesSeed[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'NestJS Advanced Topics',
    courseId: CoursesSeed[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: uuidv4(),
    title: 'Docker Networking',
    courseId: CoursesSeed[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Docker Volumes and Storage',
    courseId: CoursesSeed[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Docker Orchestration',
    courseId: CoursesSeed[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Responsive Web Design',
    courseId: CoursesSeed[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'CSS Flexbox and Grid',
    courseId: CoursesSeed[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'JavaScript for Web Designers',
    courseId: CoursesSeed[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Introduction to .NET',
    courseId: CoursesSeed[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'C# Programming Basics',
    courseId: CoursesSeed[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'ASP.NET Core Fundamentals',
    courseId: CoursesSeed[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Vue.js Basics',
    courseId: CoursesSeed[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Vue.js Components',
    courseId: CoursesSeed[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Vue.js Routing and State Management',
    courseId: CoursesSeed[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Getting Started with Flutter',
    courseId: CoursesSeed[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Flutter Widgets and Layouts',
    courseId: CoursesSeed[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'State Management in Flutter',
    courseId: CoursesSeed[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'TypeScript Basics',
    courseId: CoursesSeed[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Advanced TypeScript Features',
    courseId: CoursesSeed[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Advanced C# Programming',
    courseId: CoursesSeed[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Introduction to Kubernetes',
    courseId: CoursesSeed[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Kubernetes Deployment Strategies',
    courseId: CoursesSeed[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Introduction to HTML',
    courseId: CoursesSeed[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Introduction to CSS',
    courseId: CoursesSeed[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Advanced HTML/CSS Techniques',
    courseId: CoursesSeed[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Getting Started with Django',
    courseId: CoursesSeed[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Django Models and ORM',
    courseId: CoursesSeed[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Django Views and Templates',
    courseId: CoursesSeed[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Django Forms and Authentication',
    courseId: CoursesSeed[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Django REST Framework',
    courseId: CoursesSeed[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
